name = "ftu-voice"
pages_build_output_dir = "build"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
REPLICATE_API_TOKEN = ""
ELEVENLABS_API_KEY = ""
ANTHROPIC_API_KEY = ""
